# Generated by Django 3.2.22 on 2023-10-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('bug_type', models.CharField(choices=[('error', 'error'), ('new feature', 'new feature')], default='error', max_length=20)),
                ('report_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('to do', 'to do'), ('in progress', 'in progress'), ('done', 'done')], default='to do', max_length=20)),
            ],
        ),
    ]
